# Generated by Django 5.0.1 on 2026-03-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='basic_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='preferred_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
