# Generated by Django 5.0.1 on 2026-03-11 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_joblisting_delete_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='company',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='title',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_title',
            field=models.CharField(default='Default Job title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary',
            field=models.CharField(default='Salary TBD', max_length=100),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
