# Generated by Django 5.0.1 on 2026-03-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_joblisting_basic_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
