# Generated by Django 5.0.1 on 2026-03-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_joblisting_delete_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='apply_url',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='experience_level',
            field=models.CharField(default='Entry Level', max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_type',
            field=models.CharField(default='Full-Time', max_length=100),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
