# Generated by Django 5.0.1 on 2026-03-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_joblisting_posted_date_joblisting_apply_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='basic_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='preferred_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
