# Generated by Django 5.0.1 on 2026-03-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_joblisting_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('saved', 'Saved'), ('applied', 'Applied'), ('interview', 'Interview')], default='saved', max_length=20),
        ),
    ]
