# Generated by Django 5.0.1 on 2026-03-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_joblisting_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='key_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
