# Generated by Django 5.0.1 on 2026-03-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_joblisting_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('Saved', 'Saved'), ('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Saved', max_length=50),
        ),
    ]
