# Generated by Django 5.0.1 on 2026-03-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_joblisting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
