# Generated by Django 5.0.1 on 2026-03-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_joblisting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
