# Generated by Django 5.0.1 on 2026-03-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_joblisting_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
